# Site settings
title: Vincent Voyer
email: vincent.voyer03@gmail.com
description: "Ce site présente mes différents projets et mes différentes activités."
baseurl: ""
url: ""
twitter_username: VincentVoyer1
github_username:  VincentVoyer
paginate : 4
paginate_path : "news/:num"

# Build settings
markdown: kramdown
permalink: pretty

pygments: true
github: "vincentvoyer"