# Site settings
title: Vincent Voyer
email: vincent.voyer03@gmail.com
description: "Ce site présente mes différents projets et mes différentes activités."
baseurl: "http(s)://vincentvoyer.github.io"
url: ""
twitter_username: jekyllrb
github_username:  jekyll
paginate : 4
paginate_path : "project/:num"

# Build settings
markdown: kramdown
permalink: pretty